#!/usr/bin/env python3
"""Writes firmware/protocol-test/vectors.h from testdata/protocol-v1.json.

The header is generated at build time (make protocol-test) and gitignored: the
JSON is the one source of the known answers, for the companion's tests and for
the panel's on-device test sketch alike.

Usage: gen-firmware-vectors.py <protocol-v1.json> <vectors.h>
"""
import json
import sys


def c_bytes(hex_text):
    data = bytes.fromhex(hex_text)
    if not data:
        return "{0x00}", 0  # C forbids empty initialisers; the length says 0
    return "{" + ",".join("0x%02x" % b for b in data) + "}", len(data)


def c_string(text):
    out = []
    for ch in text:
        code = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 0x20 <= code <= 0x7E:
            out.append(ch)
        else:
            out.append("\\%03o" % code)  # octal: exactly 3 digits, never extended by what follows
    return '"' + "".join(out) + '"'


def main(source, target):
    d = json.load(open(source))
    lines = ["// Generated by scripts/gen-firmware-vectors.py from testdata/protocol-v1.json. Do not edit.",
             "#pragma once", "#include <stddef.h>", "#include <stdint.h>", ""]

    lines.append("struct HkdfCase { int number; const uint8_t* prk; size_t prk_len; const uint8_t* info; size_t info_len;"
                 " const uint8_t* ikm; size_t ikm_len; const uint8_t* salt; size_t salt_len; const uint8_t* okm; size_t okm_len; };")
    rows = []
    for i, h in enumerate(d["hkdf_rfc5869"]):
        for name in ("PRK", "info", "IKM", "salt", "OKM"):
            arr, n = c_bytes(h[name])
            lines.append("static const uint8_t hkdf%d_%s[] = %s;" % (i, name, arr))
            h["_" + name] = n
        rows.append("{%d, hkdf%d_PRK, %d, hkdf%d_info, %d, hkdf%d_IKM, %d, hkdf%d_salt, %d, hkdf%d_OKM, %d}" % (
            h["case"], i, h["_PRK"], i, h["_info"], i, h["_IKM"], i, h["_salt"], i, h["_OKM"]))
    lines.append("static const HkdfCase kHkdf[] = {%s};" % ", ".join(rows))
    lines.append("")

    lines.append("struct GcmCase { int count; bool expect_fail; const uint8_t* key; const uint8_t* iv; const uint8_t* pt; size_t pt_len;"
                 " const uint8_t* aad; size_t aad_len; const uint8_t* ct; size_t ct_len; const uint8_t* tag; };")
    rows = []
    cases = [(c, False) for c in d["aes256gcm_nist"]["encrypt"]] + [(c, True) for c in d["aes256gcm_nist"]["decrypt_fail"]]
    for i, (c, fail) in enumerate(cases):
        n = {}
        for name in ("key", "iv", "pt", "aad", "ct", "tag"):
            arr, n[name] = c_bytes(c.get(name, ""))
            lines.append("static const uint8_t gcm%d_%s[] = %s;" % (i, name, arr))
        assert n["key"] == 32 and n["iv"] == 12 and n["tag"] == 16
        rows.append("{%d, %s, gcm%d_key, gcm%d_iv, gcm%d_pt, %d, gcm%d_aad, %d, gcm%d_ct, %d, gcm%d_tag}" % (
            c["count"], "true" if fail else "false", i, i, i, n["pt"], i, n["aad"], i, n["ct"], i))
    lines.append("static const GcmCase kGcm[] = {%s};" % ", ".join(rows))
    lines.append("")

    p = d["protocol"]
    for name in ("K", "Np", "Nc"):
        arr, _ = c_bytes(p["inputs"][name])
        lines.append("static const uint8_t kProto%s[] = %s;" % (name, arr))
    for name in ("K_cp", "K_pc"):
        arr, _ = c_bytes(p[name])
        lines.append("static const uint8_t kProto%s[] = %s;" % (name.replace("_", ""), arr))
    lines.append("static const char kProtoDeviceId[] = %s;" % c_string(p["inputs"]["device_id"]))
    lines.append("static const char kProtoHello[] = %s;" % c_string(p["hello_line"]))
    lines.append("static const char kProtoAuth[] = %s;" % c_string(p["auth_line"]))
    lines.append("struct FrameVector { const char* plaintext; const char* line; };")
    for direction in ("c2p", "p2c"):
        rows = ["{%s, %s}" % (c_string(f["plaintext"]), c_string(f["line"])) for f in p["frames_" + direction]]
        lines.append("static const FrameVector kFrames_%s[] = {%s};" % (direction, ", ".join(rows)))
    lines.append("")

    r = d["reject"]
    lines.append("static const char* const kRejectBase64[] = {%s};" % ", ".join(c_string(x) for x in r["base64"]))
    lines.append("static const char* const kRejectReadings[] = {%s};" % ", ".join(
        c_string(x) for x in r["measurement_plaintexts"]))
    lines.append("static const char* const kRejectFrames[] = {%s};" % ", ".join(c_string(f["line"]) for f in r["frames"]))
    lines.append("static const size_t kLineTooLong = %d;" % r["line_too_long_bytes"])
    lines.append("")
    open(target, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
